name: Deploy Bicep file
on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'Prefix for resource names'
        required: true
        default: 'shth3'
        type: string
      emailTestOnlyRecipient:
        description: 'Email address for test emails'
        required: true
        default: 'test@contoso.com'
        type: string
      createCommunicationServices:
        description: 'Create Email Communication Services resources'
        required: true
        default: false
        type: boolean

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_ENVIRONMENT_RBAC_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/bicep-deploy@v2
      with:
        type: deployment
        operation: create
        scope: resourceGroup
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
        resource-group-name: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template-file: scripts/azure/azure-flex-env.bicep
        parameters: '{"prefix":"${{ inputs.prefix }}","emailTestOnlyRecipient":"${{ inputs.emailTestOnlyRecipient }}","createCommunicationServices":${{ inputs.createCommunicationServices }}}'
